development:
  sessions:
    default:
      database: html5jcup_dev
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: html5jcup_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
